// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $Cell from "./islands/Cell.tsx";
import * as $NumberPad from "./islands/NumberPad.tsx";
import * as $SudokuGame from "./islands/SudokuGame.tsx";
import * as $SudokuGrid from "./islands/SudokuGrid.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Cell.tsx": $Cell,
    "./islands/NumberPad.tsx": $NumberPad,
    "./islands/SudokuGame.tsx": $SudokuGame,
    "./islands/SudokuGrid.tsx": $SudokuGrid,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
