import type { ExampleBoard } from "../../types/sudoku.ts";

export const BAND_EXAMPLE: ExampleBoard = {
  board: [
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: 4, pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: 2, pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: 3, pencilmarks: [] },
    ],
    [
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: 4, pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
      { value: "", pencilmarks: [] },
    ],
  ],
  steps: [
    {
      overlays: [
        { type: "circle", cell: { x: 6, y: 0 }, color: "red" },
        { type: "circle", cell: { x: 8, y: 3 }, color: "red" },
      ],
      description: "Circles highlight the 4's at (6,0) and (8,3).",
    },
    // {
    //   overlays: [
    //     { type: "circle", cell: { x: 6, y: 0 }, color: "red" },
    //     { type: "circle", cell: { x: 8, y: 3 }, color: "red" },
    //   ],
    //   description: "Circles highlight the 4's at (6,0) and (8,3).",
    // },
  ],
};
